export const data = {
    total: 200000,
    vat: 0,
    discount: 5,
    paid: 190000,
    list: [
        {
            id: 1,
            sku: 'SP0001',
            name: 'Đắc nhân tâm',
            img: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            nums: 20,
            cost: 50000,
            discount: 5,
            total: 1000000,
        },
        {
            id: 2,
            sku: 'SP0002',
            name: 'Đắc nhân tâm',
            img: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            nums: 20,
            cost: 50000,
            discount: 5,
            total: 1000000,
        },
        {
            id: 3,
            sku: 'SP0002',
            name: 'Đắc nhân tâm',
            img: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            nums: 20,
            cost: 50000,
            discount: 5,
            total: 1000000,
        },
        {
            id: 4,
            sku: 'SP0002',
            name: 'Đắc nhân tâm',
            img: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            nums: 20,
            cost: 50000,
            discount: 5,
            total: 1000000,
        },
        {
            id: 5,
            sku: 'SP0002',
            name: 'Đắc nhân tâm',
            img: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            nums: 20,
            cost: 50000,
            discount: 5,
            total: 1000000,
        },
    ],
};
