export const data = {
    sku: 'IAN00003',
    status: 2,
    list: [
        {
            id: 'SP0001',
            sku: 'SP0001',
            name: 'Đắc nhân tâm',
            img: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0002',
            sku: 'SP0002',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0003',
            sku: 'SP0003',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0004',
            sku: 'SP0004',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0005',
            sku: 'SP0005',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0006',
            sku: 'SP0006',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0007',
            sku: 'SP0007',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0008',
            sku: 'SP0008',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0009',
            sku: 'SP0009',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0010',
            sku: 'SP0010',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0011',
            sku: 'SP0011',
            name: 'Đắc nhân tâm',
            img: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0012',
            sku: 'SP0012',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0013',
            sku: 'SP0013',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0014',
            sku: 'SP0014',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0015',
            sku: 'SP0015',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0016',
            sku: 'SP0016',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0017',
            sku: 'SP0017',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0018',
            sku: 'SP0018',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0019',
            sku: 'SP0019',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0020',
            sku: 'SP0020',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0021',
            sku: 'SP0021',
            name: 'Đắc nhân tâm',
            img: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0022',
            sku: 'SP0022',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0023',
            sku: 'SP0023',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0024',
            sku: 'SP0024',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0025',
            sku: 'SP0025',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0026',
            sku: 'SP0026',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0027',
            sku: 'SP0027',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0028',
            sku: 'SP0028',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0029',
            sku: 'SP0029',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 'SP0030',
            sku: 'SP0030',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
    ]
}