export const data12 = [
    {
        id: 'AC00001',
        name: 'Nguyễn Văn A',
        createAt: '23/12/2023 - 10:50',
        operate: 'login',
        content: 'Đăng nhập hệ thống',
    },
    {
        id: 'AC00002',
        name: 'Nguyễn Văn B',
        createAt: '23/12/2023 - 10:50',
        operate: 'create',
        content: 'Tạo đơn hàng DH0003',
    },
    {
        id: 'AC00003',
        name: 'Nguyễn Văn C',
        createAt: '23/12/2023 - 10:50',
        operate: 'update',
        content: 'Cập nhật khách hàng Phạm Công Minh',
    },
    {
        id: 'AC00004',
        name: 'Nguyễn Văn D',
        createAt: '23/12/2023 - 10:50',
        operate: 'remove',
        content: 'Xóa đơn kiểm hàng DKH0003',
    },
    {
        id: 'AC00005',
        name: 'Nguyễn Văn D',
        createAt: '23/12/2023 - 10:50',
        operate: 'remove',
        content: 'Xóa đơn kiểm hàng DKH0003',
    },
    {
        id: 'AC00006',
        name: 'Nguyễn Văn D',
        createAt: '23/12/2023 - 10:50',
        operate: 'remove',
        content: 'Xóa đơn kiểm hàng DKH0003',
    },
    {
        id: 'AC00007',
        name: 'Nguyễn Văn D',
        createAt: '23/12/2023 - 10:50',
        operate: 'remove',
        content: 'Xóa đơn kiểm hàng DKH0003',
    },
];

export const data11 = [
    {
        id: 'NV0001',
        name: 'Nguyễn Văn A',
        phone: '0235556963',
        email: 'hello@example.com',
        dateOfBirth: '28/04/2023',
        address: '252 Hai Bà Trưng, Bình Thạnh, TPHCM',
        role: 'Nhân viên bán hàng',
        isActive: true,
    },
    {
        id: 'NV0002',
        name: 'Nguyễn Văn A',
        phone: '0235556963',
        email: 'hello@example.com',
        dateOfBirth: '28/04/2023',
        address: '252 Hai Bà Trưng, Bình Thạnh, TPHCM',
        role: 'Nhân viên kho',
        isActive: false,
    },
    {
        id: 'NV0003',
        name: 'Nguyễn Văn A',
        phone: '0235556963',
        email: 'hello@example.com',
        dateOfBirth: '28/04/2023',
        address: '252 Hai Bà Trưng, Bình Thạnh, TPHCM',
        role: 'Quản lý',
        isActive: true,
    },
];

export const data10 = [
    {
        id: 'KH0001',
        name: 'Nguyễn Văn A',
        phone: '0235556963',
        email: 'hello@example.com',
        address: '252 Hai Bà Trưng, Bình Thạnh, TPHCM',
        totalSpending: 2500000,
        totalOrder: 25,
        isActive: true,
    },
    {
        id: 'KH0002',
        name: 'Nguyễn Văn B',
        phone: '0235556963',
        email: 'hello@example.com',
        address: '252 Hai Bà Trưng, Bình Thạnh, TPHCM',
        totalSpending: 2500000,
        totalOrder: 25,
        isActive: false,
    },
];

export const data9 = [
    {
        id: 'NNCC0001',
        name: 'Sách',
    },
    {
        id: 'NNCC0002',
        name: 'Khác',
    },
];

export const data8 = [
    {
        id: 'NCC0001',
        name: 'Nguyễn Văn A',
        group: 'Khác',
        email: 'kietphamkb@gmail.com',
        phone: '0112333568',
        isActive: true,
    },
    {
        id: 'NCC0002',
        name: 'Nguyễn Văn B',
        group: 'Sách',
        email: 'kietphamkb@gmail.com',
        phone: '0112333568',
        isActive: false,
    },
];

export const data7 = [
    {
        id: 'KM0001',
        name: '12.12',
        count: 100,
        start: '12/12/2023 - 11:00',
        end: '14/12/2023 - 24:00',
        status: 0,
    },
    {
        id: 'KM0002',
        name: '12.12',
        count: 1000,
        start: '12/12/2023 - 11:00',
        end: '14/12/2023 - 24:00',
        status: 1,
    },
    {
        id: 'KM0003',
        name: '12.12',
        count: 3000,
        start: '12/12/2023 - 11:00',
        end: '14/12/2023 - 24:00',
        status: 2,
    },
];

export const data6 = [
    {
        id: 'DTH0001',
        idOrder: 'DH0001',
        customerName: 'Trịnh Thăng Bình',
        isReturnProduct: 0,
        isReturnMoney: true,
        money: 175000,
        reason: 'Khác',
        dateRecieved: '27/05/2023 - 19:00',
    },
    {
        id: 'DTH0002',
        idOrder: 'DH0001',
        customerName: 'Trịnh Thăng Bình',
        isReturnProduct: 1,
        isReturnMoney: false,
        money: 200000,
        reason: 'Khác',
        dateRecieved: '27/05/2023 - 19:00',
    },
    {
        id: 'DTH0003',
        idOrder: 'DH0001',
        customerName: 'Trịnh Thăng Bình',
        isReturnProduct: 2,
        isReturnMoney: false,
        money: 200000,
        reason: 'Khác',
        dateRecieved: '27/05/2023 - 19:00',
    },
];

export const data5 = [
    {
        id: 'DH0001',
        dateCreated: '28/04/2003 - 14:00',
        customerName: 'Khách lẻ',
        staffCreated: 'Nguyễn Văn A',
        money: 200000,
    },
    {
        id: 'DH0002',
        dateCreated: '28/04/2003 - 14:00',
        customerName: 'Nguyễn Thị Cẩm Nhung',
        staffCreated: 'Nguyễn Văn A',
        money: 175000,
    },
    {
        id: 'DH0003',
        dateCreated: '28/04/2003 - 14:00',
        customerName: 'Đặng Văn Chuẩn',
        staffCreated: 'Nguyễn Văn A',
        money: 50000,
    },
];

export const data4 = [
    {
        id: 'DKH0001',
        status: 0,
        dateCreated: '28/04/2003 - 14:00',
        dateBalanced: '10/10/2023 - 07:55',
        staffCreated: 'Nguyễn Văn A',
        staffBalanced: 'Nguyễn Văn B',
    },
    {
        id: 'DKH0002',
        status: 1,
        dateCreated: '28/04/2003 - 18:23',
        dateBalanced: '10/10/2023 - 09:30',
        staffCreated: 'Nguyễn Văn A',
        staffBalanced: 'Nguyễn Văn B',
    },
    {
        id: 'DKH0003',
        status: 2,
        dateCreated: '28/04/2003 - 20:00',
        dateBalanced: '10/10/2023 - 12:52',
        staffCreated: 'Nguyễn Văn A',
        staffBalanced: 'Nguyễn Văn B',
    },
];

export const data3 = [
    {
        id: 'DNP0001',
        date: '20/11/2023 - 12:00',
        isPurchase: false,
        supplierName: 'A',
        staffName: 'Nguyễn Văn A',
    },
    {
        id: 'DNH0002',
        date: '01/02/2019 - 12:00',
        isPurchase: true,
        supplierName: 'B',
        staffName: 'Nguyễn Văn B',
    },
];

export const data2 = [
    {
        id: 'LSP0001',
        name: 'Văn phòng phẩm',
    },
    {
        id: 'LSP0002',
        name: 'Văn phòng phẩm',
    },
];

export const data = [
    {
        id: 'SP0001',
        sku: 'SP0001',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Tuổi trẻ đáng giá bao nhiêu nhiêu nhiêu nhiêu nhiêu nhiêu nhiêu nhiêu nhiêu',
        description: 'Mô tả',
        status: 1,
        type_id: 'LSP0001',
        type_name: 'Sách',
        author: 'Tom',
        price: 50000,
        cost: 25000,
        quantity: 59,
        date_create: '03/01/2015',
        publisher: 'NXB Kim Đồng',
        pusblishYear: 2002,
        tag: [],
    },
    {
        id: 'SP0002',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 1,
        type_id: 'LSP0001',
        type_name: 'Sách',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 50000,
        cost: 25000,
        quantity: 59,
        date_create: '03/01/2015',
    },
    {
        id: 'SP0003',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 1,
        type_id: 'LSP0001',
        type_name: 'Sách',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 50000,
        cost: 25000,
        quantity: 59,
        date_create: '03/01/2015',
    },
    {
        id: 'SP0004',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 1,
        type_id: 'LSP0001',
        type_name: 'Văn phòng phẩm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 150000,
        cost: 100000,
        quantity: 2000,
        date_create: '03/11/2023',
    },
    {
        id: 'SP0005',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 1,
        type_id: 'LSP0001',
        type_name: 'Văn phòng phẩm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 150000,
        cost: 100000,
        quantity: 2000,
        date_create: '03/11/2023',
    },
    {
        id: 'SP0006',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 1,
        type_id: 'LSP0001',
        type_name: 'Văn phòng phẩm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 150000,
        cost: 100000,
        quantity: 2000,
        date_create: '03/11/2023',
    },
    {
        id: 'SP0007',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Đồ chơi',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 100000,
        cost: 75000,
        quantity: 260,
        date_create: '18/06/2017',
    },
    {
        id: 'SP0008',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Đồ chơi',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 100000,
        cost: 75000,
        quantity: 260,
        date_create: '18/06/2017',
    },
    {
        id: 'SP0009',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Đồ chơi',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 100000,
        cost: 75000,
        quantity: 260,
        date_create: '18/06/2017',
    },
    {
        id: 'SP0010',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0011',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0012',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0013',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0014',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0015',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0016',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0017',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0018',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0019',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0020',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0021',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0022',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0023',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0024',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0025',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0026',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0027',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0028',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0029',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0030',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
];
