export const data = {
    sku: 'IAN00003',
    status: 2,
    list: [
        {
            id: 1,
            sku: 'SP0001',
            name: 'Đắc nhân tâm',
            img: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 2,
            sku: 'SP0002',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 3,
            sku: 'SP0003',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 4,
            sku: 'SP0004',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 5,
            sku: 'SP0005',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 6,
            sku: 'SP0006',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 7,
            sku: 'SP0007',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 8,
            sku: 'SP0005',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 9,
            sku: 'SP0006',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 10,
            sku: 'SP0007',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 11,
            sku: 'SP0001',
            name: 'Đắc nhân tâm',
            img: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 12,
            sku: 'SP0002',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 13,
            sku: 'SP0003',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 14,
            sku: 'SP0004',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 15,
            sku: 'SP0005',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 16,
            sku: 'SP0006',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 17,
            sku: 'SP0007',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 18,
            sku: 'SP0005',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 19,
            sku: 'SP0006',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 20,
            sku: 'SP0007',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 21,
            sku: 'SP0001',
            name: 'Đắc nhân tâm',
            img: 'https://inthienhang.com/wp-content/uploads/2020/03/mau-bia-sach-dep.jpg',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 22,
            sku: 'SP0002',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 23,
            sku: 'SP0003',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 24,
            sku: 'SP0004',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 25,
            sku: 'SP0005',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 26,
            sku: 'SP0006',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 27,
            sku: 'SP0007',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 28,
            sku: 'SP0005',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 29,
            sku: 'SP0006',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
        {
            id: 30,
            sku: 'SP0007',
            name: 'Đắc nhân tâm',
            img: '',
            actualexistence: 0,
            reason: 0,
            note: "",
        },
    ]
}