export const data3 = [
    {
        id: 'DNP0001',
        date: '20/11/2023',
        isPurchase: false,
        supplierName: 'A',
        staffName: 'Nguyễn Văn A',
    },
    {
        id: 'DNH0002',
        date: '01/02/2019',
        isPurchase: true,
        supplierName: 'B',
        staffName: 'Nguyễn Văn B',
    },
];

export const data2 = [
    {
        id: 'LSP0001',
        name: 'Văn phòng phẩm',
    },
    {
        id: 'LSP0002',
        name: 'Văn phòng phẩm',
    },
];

export const data = [
    {
        id: 'SP0001',
        sku: 'SP0001',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Tuổi trẻ đáng giá bao nhiêu nhiêu nhiêu nhiêu nhiêu nhiêu nhiêu nhiêu nhiêu',
        description: 'Mô tả',
        status: 1,
        type_id: 'LSP0001',
        type_name: 'Sách',
        author: 'Tom',
        price: 50000,
        cost: 25000,
        quantity: 59,
        date_create: '03/01/2015',
        publisher: 'NXB Kim Đồng',
        pusblishYear: 2002,
        tag: [],
    },
    {
        id: 'SP0002',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 1,
        type_id: 'LSP0001',
        type_name: 'Sách',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 50000,
        cost: 25000,
        quantity: 59,
        date_create: '03/01/2015',
    },
    {
        id: 'SP0003',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 1,
        type_id: 'LSP0001',
        type_name: 'Sách',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 50000,
        cost: 25000,
        quantity: 59,
        date_create: '03/01/2015',
    },
    {
        id: 'SP0004',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 1,
        type_id: 'LSP0001',
        type_name: 'Văn phòng phẩm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 150000,
        cost: 100000,
        quantity: 2000,
        date_create: '03/11/2023',
    },
    {
        id: 'SP0005',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 1,
        type_id: 'LSP0001',
        type_name: 'Văn phòng phẩm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 150000,
        cost: 100000,
        quantity: 2000,
        date_create: '03/11/2023',
    },
    {
        id: 'SP0006',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 1,
        type_id: 'LSP0001',
        type_name: 'Văn phòng phẩm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 150000,
        cost: 100000,
        quantity: 2000,
        date_create: '03/11/2023',
    },
    {
        id: 'SP0007',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Đồ chơi',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 100000,
        cost: 75000,
        quantity: 260,
        date_create: '18/06/2017',
    },
    {
        id: 'SP0008',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Đồ chơi',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 100000,
        cost: 75000,
        quantity: 260,
        date_create: '18/06/2017',
    },
    {
        id: 'SP0009',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Đồ chơi',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 100000,
        cost: 75000,
        quantity: 260,
        date_create: '18/06/2017',
    },
    {
        id: 'SP0010',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0011',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0012',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0013',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0014',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0015',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0016',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0017',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0018',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0019',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0020',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0021',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0022',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0023',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0024',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0025',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0026',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0027',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0028',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0029',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
    {
        id: 'SP0030',
        image: [
            'https://cdn0.fahasa.com/media/catalog/product/d/n/dntttttuntitled.png',
            'https://eccthai.com/wp-content/uploads/2021/01/tom-tat-dac-nhan-tam.jpg',
        ],
        name: 'Đắc nhân tâm',
        status: 0,
        type_id: 'LSP0001',
        type_name: 'Quà lưu niệm',
        group_id: 'NSP0001',
        group_name: 'Sách triết lý',
        price: 320000,
        cost: 280000,
        quantity: 120,
        date_create: '07/02/2020',
    },
];
